run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic

linters-settings:
  goimports:
    local-prefixes: github.com/miladbeigi/vaultui
  gocritic:
    enabled-tags:
      - diagnostic
      - style

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
